-
  name: Install nginx and server static website
  hosts: prd
  become: yes
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: latest

    - name: Starat nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy Web Page
      copy:
        src: index.html
        dest: /var/www/html
